# Hive OS Custom Miner manifest for 1Miner
# Archive 1miner-hive-<ver>.tar.gz must unpack to folder 1miner-hive/
CUSTOM_NAME=1miner-hive
CUSTOM_VERSION=1.0.3
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/1miner-hive/1miner.conf
CUSTOM_LOG_BASENAME=/var/log/miner/1miner-hive/1miner
CUSTOM_ALGO=saseul
