# Hive OS Custom Miner manifest for 1Miner
CUSTOM_NAME=1miner
CUSTOM_VERSION=1.0.0
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/1miner/1miner.conf
CUSTOM_LOG_BASENAME=/var/log/miner/1miner/1miner
CUSTOM_ALGO=saseul
