# HiveOS custom miner manifest for BtcMole (AMD Bitcoin Puzzle solver)

CUSTOM_NAME=btcmole
CUSTOM_VERSION=1.0.0

CUSTOM_CONFIG_FILENAME=/hive/miners/custom/btcmole/btcmole.conf
CUSTOM_LOG_BASENAME=/var/log/miner/custom/btcmole

MINER_NAME=$CUSTOM_NAME
MINER_VERSION=$CUSTOM_VERSION
MINER_CONFIG_FILENAME=$CUSTOM_CONFIG_FILENAME
