# GONKAMINER HiveOS custom miner
CUSTOM_NAME=gonkaminer
CUSTOM_VERSION=0.2.2
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/gonkaminer/conf.conf
CUSTOM_LOG_BASENAME=/var/log/miner/custom/$CUSTOM_NAME
MINER_NAME=$CUSTOM_NAME
MINER_VERSION=$CUSTOM_VERSION
MINER_CONFIG_FILENAME=$CUSTOM_CONFIG_FILENAME
