#!/usr/bin/env bash
# This file is sourced by HiveOS custom miner tooling.

. "$(dirname "${BASH_SOURCE[0]}")/h-manifest.conf"

quote() {
  printf '%q' "$1"
}

replace_template_vars() {
  local value="$1"

  value="${value//%WAL%/${WAL:-}}"
  value="${value//%EWAL%/${EWAL:-}}"
  value="${value//%ZWAL%/${ZWAL:-}}"
  value="${value//%DWAL%/${DWAL:-}}"
  value="${value//%EMAIL%/${EMAIL:-}}"
  value="${value//%WORKER_NAME%/${WORKER_NAME:-}}"
  value="${value//%WORKER%/${WORKER_NAME:-}}"

  printf '%s' "$value"
}

strip_pool_scheme() {
  local url="$1"

  url="${url#stratum+tcp://}"
  url="${url#tcp://}"

  printf '%s' "$url"
}

pool_url="${CUSTOM_URL:-pplns.techminehub.com:6001}"
pool_without_scheme="$(strip_pool_scheme "$pool_url")"
pool_authority="${pool_without_scheme%%/*}"
pool_host="${pool_authority%%:*}"
pool_port="${pool_authority##*:}"

if [[ "$pool_port" == "$pool_authority" || -z "$pool_port" ]]; then
  pool_port="6001"
fi

wallet_template="${CUSTOM_TEMPLATE:-%WAL%.%WORKER_NAME%}"
miner_user="$(replace_template_vars "$wallet_template")"
miner_pass="${CUSTOM_PASS:-x}"
threads="${EXCC_NATIVE_THREADS:-$(nproc 2>/dev/null || echo 1)}"
range="${EXCC_NATIVE_RANGE:-1}"
solver_timeout="${EXCC_NATIVE_SOLVER_TIMEOUT:-900}"
extra_args="${CUSTOM_USER_CONFIG:-}"

if [[ -z "$miner_user" || "$miner_user" == *%WAL%* ]]; then
  echo "EXCC wallet template is missing. Set HiveOS wallet/worker template to %WAL%.%WORKER_NAME%." >&2
  return 1 2>/dev/null || exit 1
fi

mkdir -p "$(dirname "$CUSTOM_CONFIG_FILENAME")"

{
  echo "# Generated by h-config.sh. Edit HiveOS flight sheet values instead of this file."
  printf 'EXCC_NATIVE_POOL=%s\n' "$(quote "stratum+tcp://${pool_host}:${pool_port}")"
  printf 'EXCC_NATIVE_USER=%s\n' "$(quote "$miner_user")"
  printf 'EXCC_NATIVE_PASS=%s\n' "$(quote "$miner_pass")"
  printf 'EXCC_NATIVE_THREADS=%s\n' "$(quote "$threads")"
  printf 'EXCC_NATIVE_RANGE=%s\n' "$(quote "$range")"
  printf 'EXCC_NATIVE_SOLVER_TIMEOUT=%s\n' "$(quote "$solver_timeout")"
  printf 'EXTRA_ARGS=%s\n' "$(quote "$extra_args")"
  printf 'EXCC_ALGO=%s\n' "$(quote EQUI144_5)"
  printf 'EXCC_COIN=%s\n' "$(quote EXCC)"
} > "$CUSTOM_CONFIG_FILENAME"
