#!/usr/bin/env bash
# GONKAMINER bootstrap — idempotent setup for HiveOS / AMD (no fragile venv required).
set -uo pipefail

MINER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS="${MINER_ROOT}/scripts"
PYDEPS="${MINER_ROOT}/pydeps"
VENV="${MINER_ROOT}/.venv"
STAMP="${MINER_ROOT}/.bootstrap_ok"
LOG="${MINER_ROOT}/bootstrap.log"

if [[ -d "${MINER_ROOT}/vendor/gonka-pow/pow" ]]; then
  POW_DIR="${MINER_ROOT}/vendor/gonka-pow"
elif [[ -d "${MINER_ROOT}/vendor/pow" ]]; then
  POW_DIR="${MINER_ROOT}/vendor"
else
  echo "ERROR: vendor/pow missing in ${MINER_ROOT}"
  exit 1
fi

log() { echo "[bootstrap] $*" | tee -a "$LOG"; }

install_os_packages() {
  command -v apt-get >/dev/null 2>&1 || return 0
  export DEBIAN_FRONTEND=noninteractive
  log "Installing OS packages (python3-pip, python3-venv) ..."
  apt-get update -qq 2>>"$LOG" || true
  apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv python3.10-venv \
    ca-certificates curl wget 2>>"$LOG" || true
}

detect_rocm_index() {
  local ver
  for ver in 6.4 6.3 6.2 6.1 6.0 5.7; do
    [[ -d "/opt/rocm-${ver}" ]] && { echo "https://download.pytorch.org/whl/rocm${ver}"; return; }
  done
  if [[ -d /opt/rocm/lib ]]; then
    ver="$(basename "$(ls -d /opt/rocm-* 2>/dev/null | head -1)" 2>/dev/null | sed 's/rocm-//')"
    [[ -n $ver ]] && { echo "https://download.pytorch.org/whl/rocm${ver}"; return; }
  fi
  echo "https://download.pytorch.org/whl/rocm6.2"
}

pydeps_ready() {
  PYTHONPATH="${PYDEPS}:${POW_DIR}" python3 - <<'PY' 2>/dev/null
import sys
try:
    import torch, uvicorn, fastapi
except ImportError:
    sys.exit(1)
hip = getattr(torch.version, "hip", None)
if not hip or not torch.cuda.is_available():
    sys.exit(1)
sys.exit(0)
PY
}

venv_ready() {
  [[ -x "${VENV}/bin/python" ]] && "${VENV}/bin/python" - <<'PY' 2>/dev/null
import sys
try:
    import torch, uvicorn, fastapi, pip
except ImportError:
    sys.exit(1)
hip = getattr(torch.version, "hip", None)
if not hip or not torch.cuda.is_available():
    sys.exit(1)
sys.exit(0)
PY
}

install_pydeps() {
  local rocm_index="${PYTORCH_ROCM_INDEX:-$(detect_rocm_index)}"
  mkdir -p "$PYDEPS"
  log "Installing Python deps to ${PYDEPS} (no venv) ..."
  python3 -m pip install --upgrade pip wheel 2>>"$LOG"
  python3 -m pip install --target "$PYDEPS" \
    -r "${MINER_ROOT}/requirements.txt" 2>>"$LOG"
  log "Installing ROCm PyTorch from ${rocm_index} (may take 5-15 min) ..."
  python3 -m pip install --target "$PYDEPS" \
    torch torchvision torchaudio --index-url "$rocm_index" 2>>"$LOG"
}

install_venv_path() {
  log "Fallback: using .venv ..."
  bash "${SCRIPTS}/setup-venv.sh" "$VENV" 2>>"$LOG" || return 1
  export PYTORCH_ROCM_INDEX="${PYTORCH_ROCM_INDEX:-$(detect_rocm_index)}"
  bash "${SCRIPTS}/install-rocm-torch.sh" "$VENV" 2>>"$LOG" || return 1
  "${VENV}/bin/pip" install -q -r "${MINER_ROOT}/requirements.txt" 2>>"$LOG"
}

write_runner() {
  cat > "${MINER_ROOT}/.python_env" <<EOF
# auto-generated by bootstrap.sh
export GONKAMINER_PYMODE="${PYMODE}"
export GONKAMINER_PYDEPS="${PYDEPS}"
export GONKAMINER_VENV="${VENV}"
export GONKAMINER_POW_DIR="${POW_DIR}"
EOF
}

main() {
  : > "$LOG"
  log "GONKAMINER bootstrap starting in ${MINER_ROOT}"

  if [[ -f $STAMP ]] && { pydeps_ready || venv_ready; }; then
    log "Bootstrap already OK (stamp ${STAMP})"
    if [[ -d $PYDEPS ]] && pydeps_ready; then PYMODE=pydeps
    else PYMODE=venv; fi
    write_runner
    exit 0
  fi

  install_os_packages
  rm -f "$STAMP"
  rm -rf "$PYDEPS"
  # keep .venv for fallback only

  PYMODE=pydeps
  if ! install_pydeps || ! pydeps_ready; then
    log "pydeps path failed — trying venv fallback"
    rm -rf "$PYDEPS"
    PYMODE=venv
    if ! install_venv_path || ! venv_ready; then
      log "ERROR: bootstrap failed — run: bash ${SCRIPTS}/doctor.sh"
      exit 1
    fi
  fi

  write_runner
  date -Iseconds > "$STAMP"
  log "Bootstrap OK (mode=${PYMODE})"
}

main "$@"
