# SUPERHERO - BTX (btx-matmul) custom miner for HiveOS / AMD

CUSTOM_NAME=superhero
CUSTOM_VERSION=0.2.11
CUSTOM_BUILD=1
CUSTOM_MINERBIN=superhero
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/superhero/config.conf
CUSTOM_LOG_BASENAME=/var/log/miner/custom/superhero
