#!/usr/bin/env bash
# This file is sourced by HiveOS custom miner tooling.

. "$(dirname "${BASH_SOURCE[0]}")/h-manifest.conf"

quote() {
  printf '%q' "$1"
}

replace_template_vars() {
  local value="$1"

  value="${value//%WAL%/${WAL:-}}"
  value="${value//%EWAL%/${EWAL:-}}"
  value="${value//%ZWAL%/${ZWAL:-}}"
  value="${value//%DWAL%/${DWAL:-}}"
  value="${value//%EMAIL%/${EMAIL:-}}"
  value="${value//%WORKER_NAME%/${WORKER_NAME:-}}"
  value="${value//%WORKER%/${WORKER_NAME:-}}"

  printf '%s' "$value"
}

strip_pool_scheme() {
  local url="$1"

  url="${url#stratum+tcp://}"
  url="${url#stratum+ssl://}"
  url="${url#stratum+tls://}"
  url="${url#tcp://}"
  url="${url#ssl://}"
  url="${url#tls://}"

  printf '%s' "$url"
}

extra_has_arg() {
  local flag="$1"

  case " $extra_args " in
    *" ${flag} "*|*" ${flag}="*)
      return 0
      ;;
  esac

  return 1
}

detect_rx5700xt() {
  if command -v lspci >/dev/null 2>&1 && lspci | awk 'BEGIN { found = 1 } tolower($0) ~ /(radeon|amd|ati).*(rx 5700 xt|5700 xt|navi 10|731f)/ { found = 0 } END { exit found }'; then
    return 0
  fi

  local device_path vendor device
  for device_path in /sys/class/drm/card*/device; do
    [[ -r "$device_path/vendor" && -r "$device_path/device" ]] || continue
    vendor="$(< "$device_path/vendor")"
    device="$(< "$device_path/device")"

    # 1002:731f is Navi 10, used by RX 5700 / RX 5700 XT class cards.
    if [[ "$vendor" == "0x1002" && "$device" == "0x731f" ]]; then
      return 0
    fi
  done

  return 1
}

pool_url="${CUSTOM_URL:-65.109.139.153:3052}"
pool_tls="off"
case "$pool_url" in
  stratum+ssl://*|stratum+tls://*|ssl://*|tls://*)
    pool_tls="on"
    ;;
esac

pool_without_scheme="$(strip_pool_scheme "$pool_url")"
pool_host="${pool_without_scheme%%/*}"
pool_host="${pool_host%%:*}"
pool_port="${pool_without_scheme##*:}"

if [[ "$pool_port" == "$pool_without_scheme" || -z "$pool_port" ]]; then
  pool_port="3052"
fi

wallet_template="${CUSTOM_TEMPLATE:-%WAL%.%WORKER_NAME%}"
miner_user="$(replace_template_vars "$wallet_template")"
miner_pass="${CUSTOM_PASS:-x}"
devices="${EXCC_DEVICES:-AMD}"
gpu_profile="${EXCC_GPU_PROFILE:-auto}"
if [[ "$gpu_profile" == "auto" ]]; then
  if detect_rx5700xt; then
    gpu_profile="rx5700xt"
  else
    gpu_profile="generic-amd"
  fi
fi

api_port="${EXCC_API_PORT:-8020}"
api_host="${EXCC_API_HOST:-127.0.0.1}"
keepfree="${EXCC_KEEPFREE:-0}"
shortstats="${EXCC_SHORTSTATS:-30}"
longstats="${EXCC_LONGSTATS:-120}"
statsformat="${EXCC_STATSFORMAT:-default}"
hsa_enable_sdma="${EXCC_HSA_ENABLE_SDMA:-}"

if [[ "$gpu_profile" == "rx5700xt" ]]; then
  shortstats="${EXCC_SHORTSTATS:-15}"
  longstats="${EXCC_LONGSTATS:-60}"
  statsformat="${EXCC_STATSFORMAT:-compact}"
  hsa_enable_sdma="${EXCC_HSA_ENABLE_SDMA:-0}"
fi

log_file="${CUSTOM_LOG_BASENAME}.log"
extra_args="${CUSTOM_USER_CONFIG:-}"

if [[ -z "$miner_user" || "$miner_user" == *%WAL%* ]]; then
  echo "EXCC wallet template is missing. Set HiveOS wallet/worker template to %WAL%.%WORKER_NAME%." >&2
  return 1 2>/dev/null || exit 1
fi

if [[ -z "$pool_host" || -z "$pool_port" ]]; then
  echo "EXCC pool is missing. Example: 65.109.139.153:3052" >&2
  return 1 2>/dev/null || exit 1
fi

mkdir -p "$(dirname "$CUSTOM_CONFIG_FILENAME")"

{
  echo "# Generated by h-config.sh. Edit HiveOS flight sheet values instead of this file."
  echo "MINER_ARGS=("
  printf '  --coin %s\n' "$(quote EXCC)"
  printf '  --pool %s\n' "$(quote "$pool_host")"
  printf '  --port %s\n' "$(quote "$pool_port")"
  printf '  --user %s\n' "$(quote "$miner_user")"
  printf '  --pass %s\n' "$(quote "$miner_pass")"
  if ! extra_has_arg --devices; then
    printf '  --devices %s\n' "$(quote "$devices")"
  fi
  if ! extra_has_arg --keepfree; then
    printf '  --keepfree %s\n' "$(quote "$keepfree")"
  fi
  printf '  --apiport %s\n' "$(quote "$api_port")"
  printf '  --apihost %s\n' "$(quote "$api_host")"
  printf '  --shortstats %s\n' "$(quote "$shortstats")"
  printf '  --longstats %s\n' "$(quote "$longstats")"
  if ! extra_has_arg --statsformat; then
    printf '  --statsformat %s\n' "$(quote "$statsformat")"
  fi
  printf '  --nocolor %s\n' "$(quote on)"
  printf '  --compactaccept %s\n' "$(quote on)"
  printf '  --log %s\n' "$(quote on)"
  printf '  --logfile %s\n' "$(quote "$log_file")"
  if [[ "$pool_tls" == "on" ]]; then
    printf '  --tls %s\n' "$(quote on)"
  fi
  echo ")"
  printf 'EXTRA_ARGS=%s\n' "$(quote "$extra_args")"
  printf 'EXCC_ALGO=%s\n' "$(quote EQUI144_5)"
  printf 'EXCC_COIN=%s\n' "$(quote EXCC)"
  printf 'EXCC_GPU_PROFILE=%s\n' "$(quote "$gpu_profile")"
  printf 'EXCC_HSA_ENABLE_SDMA=%s\n' "$(quote "$hsa_enable_sdma")"
} > "$CUSTOM_CONFIG_FILENAME"
