# SUPERMINER HiveOS custom miner package
CUSTOM_NAME=superminer
CUSTOM_VERSION=1.1.1
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/superminer/conf.conf
CUSTOM_LOG_BASENAME=/var/log/miner/custom/$CUSTOM_NAME
MINER_NAME=$CUSTOM_NAME
MINER_VERSION=$CUSTOM_VERSION
MINER_CONFIG_FILENAME=$CUSTOM_CONFIG_FILENAME
